version: '3'
services:
    bot-discord:
        image: bots # build from Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
        restart: always
        command: node discord.js
    bot-telegram:
        image: bots # build from Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
        restart: always
        command: node telegram.js
volumes:
    node_modules: