version: '3'
services:
    bot-discord:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
        restart: always
        command: node discord.js
    bot-telegram:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
        restart: always
        command: node telegram.js
    bot-twitter:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
        # restart: always
        command: node twitter.js
volumes:
    node_modules: